FROM golang:1.17-alpine AS BUILD-STEP

# Update certificates, otherwise API calls wont work
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*

# Create and move to working directory
WORKDIR /build

# Copy code into the container
COPY . ./
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go build -o api-binary cmd/api/*.go

WORKDIR /dist

RUN cp /build/api-binary .

FROM scratch

COPY --from=BUILD-STEP /build/api-binary /
COPY --from=BUILD-STEP etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

#COPY .env .env

ENTRYPOINT ["/api-binary"]
