version: "3.9"

services:
  my-rabbitmq:
    image: rabbitmq:3.9.3-management-alpine
    container_name: my-rabbitmq
    ports:
        - 5672:5672
        - 15672:15672 # For RabbitMQ GUI
    volumes:
        - /tmp/devops-app/:/var/lib/rabbitmq:rw
    # restart: on-failure
    networks:
        - dev-network

  mongodb:
    image: mongo:5.0.2
    container_name: mongodb
    volumes:
    - /tmp/mongodb/database:/data/db
    ports:
      - 27017:27017
    # restart: on-failure
    networks:
      - dev-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      PUID: 1000
      PGID: 1000

  redis:
    image: redis:6.2
    container_name: my-redis
    ports:
      - 6379:6379
    networks:
      - dev-network

  # GUI for MongoDB
  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: "27017"
    networks:
      - dev-network
    ports:
      - 8081:8081
    # restart: on-failure
    depends_on:
      - mongodb
    volumes:
      - /tmp/mongodb/database:/data/db

networks:
  dev-network:
    driver: bridge
